### ISSUE TITLE
Feature Request: ToolbarController/ClickThruBlocker support

### ISSUE THREAD

**Issue by StoneBlue** [linuxgurugamer/NodeHelper#5]
LGG, since your fork of NH seems to be the most current, (inc. PhineasFreak's fork), *and* since TC & CTB are both yours, any possibility of when you get a spare moment (i kno...lol), could you consider this, please?... 
At *least* the CTB support... between the default "spawn" position of the NH windows, (right over the part icons, in *my* screen size of 1440x900 and anything smaller), and having *three* seperate NH windows to sometimes work with, *not* having CTB support has been about my only peeve with NH over the years.
As always, THANX for keeping yet another *must-have* mod, for many people, going...

**Comment by linuxgurugamer** [comment]
Sure, it won't be too difficult.  Maybe this evening.
And my screen size is 3440x1440

**Comment by linuxgurugamer** [comment]
Just released it

**Comment by StoneBlue** [comment]
As always, THANX a bunch :)
