### ISSUE TITLE
Problem saving data for parts having names with underscores

### ISSUE THREAD

**Issue by whale2** [linuxgurugamer/NodeHelper#6]
If part name has an underscore, it is being replaced with dot by ksp. So, for instance, if part name is
"B9.Body.Mk2.Cargo.Bay.1m", GameDatabase contains instead "B9_Body_Mk2_Cargo_Bay_1m".
As a result, no config found and no file generated.
Suggested fix:

in https://github.com/linuxgurugamer/NodeHelper/blob/master/NodeHelper/NodeHelper.cs#L1142:
`return parts[0].Replace('.','_');`

**Comment by linuxgurugamer** [comment]
But what about those instances when a part name actually HAS a dot?  Same goes for a part name with a space in it, it's replaced by a dot.
I'm not sure there is a solution which satisfies all conditions without using MM to add a field to save the original part name.

**Comment by whale2** [comment]
Not sure I follow. If the part name, as defined in .cfg, has dots, dots are replaced with underscores by the game. I don't think GameDatabase could actually contain parts with dots in the name.

**Comment by linuxgurugamer** [comment]
yes, but parts can have spaces and underscores, both of which are replaced by dots.

**Comment by linuxgurugamer** [comment]
Also, that method is used to get a normalized name for the GameDatabase, it can't be changed like that.
I'm adding a new module (similiar to PartInfo) which will contain the original name

**Comment by linuxgurugamer** [comment]
Oh, I think I see. Will get back to this later, your suggestion may actually be correct.

**Comment by linuxgurugamer** [comment]
Thank you, I'm implementing your fix now
